services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: Ena1dio2tria3!
      POSTGRES_DB: dfm
      PGDATA: /database
    volumes:
      - ./Database:/database
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@dfm.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-Ena1dio2tria3!}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./PgAdmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge